name: Deploy   #这里的名字就是deploy.yml(工作流)文件的名字
on:
  push:
    branches:
      - main      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['lts/fermium']
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'main'
          persist-credentials: false
          fetch-depth: 0
        env:
          TZ: Asia/Shanghai
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}

      #第一种方式打包
      # - name: Install dependencies
      #   run: npm install
      # - name: npm audit fix
      #   run: npm audit fix       
      # - name: Use yarn create vlib
      #   run: yarn create vlib
      # - name: Build My Blog
      #   run: npm run build

      #第二种方式打包
      # https://classic.yarnpkg.com/en/docs/cli/install
      - name: perpare delete proxy
        run: yarn config delete proxy
        
      - name: perpare delete https-proxy
        run: yarn config delete https-proxy
        
      - name: perpare check registry 
        run: yarn config get registry 

      - name: perpare cache clean
        run: yarn cache clean --all 
        
      # - name: perpare edit registry
      #   run: yarn config set registry https://registry.npmmirror.com

      - name: updrage
        run: yarn set version stable
      - name: version
        run: yarn --version 
      - name: perpare check config list
        run: yarn config list
        
      - name: Install dependencies
        run: yarn install --registry=https://registry.npmmirror.com --force --audit --verbose
        
      - name: Build My Blog
        run: yarn run build
      
      - name: Deploy to Pages
        env:
         TZ: Asia/Shanghai
        run: |
         cd .vitepress/dist
         git config --global init.defaultBranch main
         git config --global --add safe.directory "*"
         git init
         git config user.name "JourneyFlower"
         git config user.email "${{ secrets.GIT_EMAIL }}"
         git add .
         git commit -m "Deploying to blog-pages from @ $GITHUB_SHA in $(date +"%Y年%m月%d日 %T %Z")"
         git push -f https://JourneyFlower:${{ secrets.ACCESS_TOKEN }}@github.com/JourneyFlower/blog.git main:blog-pages
         cd - 
